### ISSUE TITLE
Boolean Operations

### ISSUE THREAD

**Issue by AdmiralPellaeon** [paulbuechner/occutils#3]
### Description

Hi,

it would be helpful if the library would cover all OCC boolean operations, not only fuse and cut.

Best regards

### Problem Statement/Justification

I want to use the boolean section which is not available by OCCutils atm.

### Proposed Solution or API

TopoDS_Shape aShape = occutils::boolean::Section(aBox, anotherBox);

**Comment by paulbuechner** [comment]
@AdmiralPellaeon Hey, I extended the generic utilities around boolean operations to now also include common as well as section utils. Feel free to leave some feedback.

Cheers!
